<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = 
        [
            [
                'nama' => 'Cake Keju',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lemper',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],                            
            [
                'nama' => 'Roll Soes Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Soes Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ], 
            [
                'nama' => 'Pie Daging',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Soes Maker',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Semar Mendem',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Sosis Solo',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Risoles',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpia',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kroket',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Tahu Bihun',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Gabin Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Martabak',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Risoles Mayonaise',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 3400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pastel',
                'kategori' => 'Kue Asin',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Keju',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lemper',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],                            
            [
                'nama' => 'Roll Soes Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Soes Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ], 
            [
                'nama' => 'Pie Daging',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Soes Maker',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Semar Mendem',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Sosis Solo',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Risoles',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpia',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kroket',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Tahu Bihun',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Gabin Ragout',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Martabak',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Risoles Mayonaise',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1850,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pastel',
                'kategori' => 'Kue Asin',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pudding',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kletikan',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Coklat',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Spiku',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Long Soes',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Soes Vla',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpur',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpur Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Bikang',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Apem',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Apem Selang',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pie Buah Mandarin',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pisang Gulung Coklat',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pudding',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],            
            [
                'nama' => 'Cake Coklat',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Spiku',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Long Soes',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Soes Vla',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpur',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lumpur Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],                                    
            [
                'nama' => 'Pie Buah Mandarin',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Pisang Gulung Coklat',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Tart Mambo',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Tart Selai',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Mini',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Caramel',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Talam Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Donat Kentang',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2750,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roti Kukus',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Brownies',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kue Mangkok',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Bika Ambon',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Ongol-Ongol',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Onde-Onde',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 2400,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kue Mini Nampan Kecil',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 42500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kue Mini Nampan Besar',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 42500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Tart Mambo',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Tart Selai',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roll Mini',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1700,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Cake Caramel',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Talam Pandan',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Donat Kentang',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Roti Kukus',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Brownies',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kue Mangkok',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Bika Ambon',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Ongol-Ongol',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Onde-Onde',
                'kategori' => 'Kue Manis',
                'varian' => 'Mini',
                'harga_satuan' => 1500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Lapis Ubi Ungu',
                'kategori' => 'Kue Manis',
                'varian' => 'Normal',
                'harga_satuan' => 35000,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 2',
                'kategori' => 'Kotak',
                'varian' => 'Pendek',
                'harga_satuan' => 500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 2',
                'kategori' => 'Kotak',
                'varian' => 'Tinggi',
                'harga_satuan' => 500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 3',
                'kategori' => 'Kotak',
                'varian' => 'Pendek',
                'harga_satuan' => 500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 3',
                'kategori' => 'Kotak',
                'varian' => 'Tinggi',
                'harga_satuan' => 500,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 4',
                'kategori' => 'Kotak',
                'varian' => 'Normal',
                'harga_satuan' => 600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 5',
                'kategori' => 'Kotak',
                'varian' => 'Normal',
                'harga_satuan' => 600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 3 Biru',
                'kategori' => 'Kotak',
                'varian' => 'Tinggi',
                'harga_satuan' => 1300,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Kotak Isi 4 Biru',
                'kategori' => 'Kotak',
                'varian' => 'Tinggi',
                'harga_satuan' => 1600,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
            [
                'nama' => 'Ongkos Kirim',
                'kategori' => 'Lainnya',
                'varian' => 'Normal',
                'harga_satuan' => 5000,                
                'created_at' => Carbon::now('GMT+7'),
                'updated_at' => Carbon::now('GMT+7'),
            ],
        ];                        

        DB::table('products')->insert($products);
    }
}
